# Auth service URL
aaauth.url : https://auth.openshift.io
auth.url : https://auth.prod-preview.openshift.io
xxauth.url : http://localhost:8089

# Openshift Proxy URL
osoproxy.url : https://f8osoproxy-test-dsaas-preview.b6ff.rh-idev.openshiftapps.com

# enable tenant service
xxxtenant.serviceurl : http://localhost:8080