version: '0.2'

services:
  db:
    image: centos/postgresql-95-centos7
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_ADMIN_PASSWORD: mysecretpassword
    volumes:
      - dbstore:/var/lib/pgsql/data

  core:
    image: almightycore/almighty-core:latest
    environment:
      ALMIGHTY_POSTGRES_HOST: db
    ports:
      - "8080:8080"

volumes:
  dbstore:
    size: 1Gi
    mode: ReadWriteOnce

