version: '2.1'
services:
  postgres_integration_test:
    image: registry.centos.org/postgresql/postgresql:9.6
    network_mode: "bridge"
    ports:
      - "5432"
    environment:
      POSTGRESQL_ADMIN_PASSWORD: mysecretpassword
    healthcheck:
      test: "bash -c 'pg_isready -h localhost -p 5432 -q -U postgres'"
      interval: 3s
      timeout: 7s
      retries: 5
  db-auth:
    image: registry.centos.org/postgresql/postgresql:9.6
    ports:
      - "5433:5432"
    environment:
      POSTGRESQL_ADMIN_PASSWORD: mysecretpassword
  auth:
    image: docker.io/fabric8/fabric8-auth:latest
#    command: -config /usr/local/auth/etc/config.yaml
    environment:
      AUTH_WIT_URL: "http://localhost:8080"
      AUTH_DEVELOPER_MODE_ENABLED: "true"
      AUTH_POSTGRES_HOST: db-auth
      AUTH_POSTGRES_PORT: 5432
    ports:
      - "8089:8089"
    depends_on:
      - db-auth

