apiVersion: v1
kind: Secret
metadata:
  name: api
type: Opaque
data:
  db.host: ZGI=
  db.port: NTQzMg==
  db.user: cG9zdGdyZXM=
  db.password: bXlzZWNyZXRwYXNzd29yZA==
  keycloak.realm: ZmFicmljOAo=
